language: php

sudo: false

matrix:
  include:
    - php: hhvm
    - php: 7.1
    - php: 7.2
    - php: 7.3

install:
  - composer install

script:
  - bin/phpspec run --format=pretty
  - bin/behat --format=pretty
